/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bauDoTesouro.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bauDoTesouro.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.958, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[2.129, 0, 0]}>
            <mesh geometry={nodes.baixo1.geometry} material={materials['T_Mimic.002']} position={[166.027, 6.907, 1.676]} scale={33.896} />
            <mesh geometry={nodes.baixo2.geometry} material={materials['T_Mimic.002']} position={[164.907, 6.907, 4.089]} scale={33.896} />
            <mesh geometry={nodes.baixo3.geometry} material={materials['T_Mimic.002']} position={[164.907, 6.907, 12.47]} rotation={[-0.204, 0, 0]} scale={33.896} />
            <mesh geometry={nodes.baixo4.geometry} material={materials['T_Mimic.002']} position={[170.531, 10.752, 3.424]} rotation={[0.021, 0.056, 0.08]} scale={33.896} />
            <mesh geometry={nodes.baixo5.geometry} material={materials['T_Mimic.002']} position={[169.739, 26.165, 5.127]} rotation={[0, 0, 0.214]} scale={33.896} />
            <mesh geometry={nodes.baixo6.geometry} material={materials['T_Mimic.002']} position={[155.229, -21.924, 3.609]} rotation={[0, 0, -0.414]} scale={33.896} />
            <mesh geometry={nodes.baixo7.geometry} material={materials['T_Mimic.002']} position={[160.727, 6.907, 4.957]} scale={33.896} />
            <mesh geometry={nodes.baixo8.geometry} material={materials['T_Mimic.002']} position={[156.257, 6.907, 2.778]} scale={33.896} />
            <mesh geometry={nodes.cima1.geometry} material={materials['T_Mimic.002']} position={[161.283, -35.983, -22.651]} rotation={[0.531, -0.144, -0.24]} scale={39.622} />
            <mesh geometry={nodes.cima2.geometry} material={materials['T_Mimic.002']} position={[190.393, 12.609, -20.72]} rotation={[0.521, 0.177, 0.297]} scale={39.622} />
            <mesh geometry={nodes.cima3.geometry} material={materials['T_Mimic.002']} position={[177.823, -7.195, -18.65]} rotation={[0.548, 0, 0]} scale={39.622} />
            <mesh geometry={nodes.cima4.geometry} material={materials['T_Mimic.002']} position={[177.823, -7.195, -22.285]} rotation={[0.548, 0, 0]} scale={39.622} />
            <mesh geometry={nodes.cima5.geometry} material={materials['T_Mimic.002']} position={[177.823, -26.016, 12.478]} rotation={[-0.005, 0, 0]} scale={39.622} />
            <mesh geometry={nodes.cima6.geometry} material={materials['T_Mimic.002']} position={[177.823, -7.195, -20.032]} rotation={[0.548, 0, 0]} scale={39.622} />
            <mesh geometry={nodes.SM_Mimic_T_Mimic_0070.geometry} material={materials['T_Mimic.002']} scale={0} />
          </group>
        </group>
      </group>
      <group position={[0, 0.48, 0.349]} rotation={[-2.686, -1.524, 0.385]} scale={[0.104, 0.104, 0.085]}>
        <group rotation={[0.008, -0.004, -0.184]}>
          <mesh geometry={nodes.Object_2001.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Object_2001_1.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Object_2001_2.geometry} material={materials['Material.001']} />
        </group>
      </group>
      <mesh geometry={nodes.Lid.geometry} material={materials['chests.002']} position={[-0.172, 0.429, -0.285]} rotation={[1.565, 0, 0]} />
      <mesh geometry={nodes.Box.geometry} material={materials['chests.002']} />
      <mesh geometry={nodes.Gold.geometry} material={materials['chests.002']} position={[0, 0.379, 0]} />
    </group>
  )
}

useGLTF.preload('/bauDoTesouro.glb')
