/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 porta.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/porta.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.doorway.geometry} material={materials['Dungeon_passage.001']} position={[0.019, -0.084, 0.079]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.door.geometry} material={materials['Dungeon_passage.002']} position={[0.019, -0.084, 0.089]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[0, 0.69, 0.144]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.751, 0.751, 0.575]} />
    </group>
  )
}

useGLTF.preload('/porta.glb')
