/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/porta_2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/porta_2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.doorway.geometry} material={materials['Dungeon_passage.001']} position={[0.019, -0.084, 0.079]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.door.geometry} material={materials['Dungeon_passage.002']} position={[0.019, -0.084, 0.089]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[0, 1, 1.134]} />
    </group>
  )
}

useGLTF.preload('/porta_2.glb')
