/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gemas.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useRef } from 'react'
import { useFrame } from '@react-three/fiber'

export default function Gemas({formato = null ,cor = null, ...props}) {

  const { nodes, materials } = useGLTF('/modelos_cenas/mina/gemas.glb')
  const atraso = useRef(Math.random() * Math.PI * 2)
  const brilho = useRef(null)
  const gema = useRef(null)
  const hover = useRef(0)

  const material_cores = {
    vermelho : materials['V_01.001'],
    azul : materials['V_02.001'],
    verde : materials['V_03.001'],
    laranja : materials['V_04.001'],
    roxo : materials['V_05.001']

  }

  const formatos = {

    brilhante : {
      roxo : nodes.Gemstone_01.geometry,
      laranja : nodes.Gemstone_01001.geometry,
      verde : nodes.Gemstone_01002.geometry,
      azul : nodes.Gemstone_01003.geometry,
      vermelho : nodes.Gemstone_01004.geometry,      
    },

    gota : {
      roxo : nodes.Gemstone_02.geometry,
      laranja : nodes.Gemstone_02004.geometry,
      verde : nodes.Gemstone_02003.geometry,
      azul : nodes.Gemstone_02002.geometry,
      vermelho : nodes.Gemstone_02001.geometry,
    },

    almofada : {
      roxo : nodes.Gemstone_03.geometry,
      laranja : nodes.Gemstone_03001.geometry,
      verde : nodes.Gemstone_03002.geometry,
      azul : nodes.Gemstone_03003.geometry,
      vermelho : nodes.Gemstone_03004.geometry,
    },

    esmeralda : {
      roxo : nodes.Gemstone_04.geometry,
      laranja : nodes.Gemstone_04001.geometry,
      verde : nodes.Gemstone_04002.geometry,
      azul : nodes.Gemstone_04003.geometry,
      vermelho : nodes.Gemstone_04004.geometry,
    },

    trapezio : {
      roxo : nodes.Gemstone_05.geometry,
      laranja : nodes.Gemstone_05001.geometry,
      verde : nodes.Gemstone_05002.geometry,
      azul : nodes.Gemstone_05003.geometry,
      vermelho : nodes.Gemstone_05004.geometry,
    }

  }

  const gerar_formato = (formato_base = null, cor = null) => {

    if (!formato_base){

      const formatos_disponiveis = Object.keys(formatos)

      formato_base = formatos_disponiveis[Math.floor(Math.random() * formatos_disponiveis.length)]

    }

    if (!cor){

      const cores_disponiveis = Object.keys(material_cores)

      cor = cores_disponiveis[Math.floor(Math.random() * cores_disponiveis.length)]

    }

    console.log(formato_base, cor)   

    const formatos_disponiveis = formatos[formato_base]

    return [formatos_disponiveis[cor], cor]

  }

  const [formato_escolhido, cor_escolhida] = gerar_formato(formato, cor)

  useFrame(({clock}) => {

    if (!gema.current) return
    
    const delta = clock.getElapsedTime()

    gema.current.rotation.y += (.005 + hover.current * .008)

    gema.current.emissiveIntensity = Math.sin(delta) * 50.5

  })

  return (
    <group {...props} dispose={null}>
      <mesh 
      ref={gema}
      geometry={formato_escolhido} 
      material={material_cores[cor_escolhida]}
      onPointerOver={() => {hover.current = 1}}
      onPointerLeave={() => {hover.current = 0}}/>

    </group>
  )
}

useGLTF.preload('/modelos_cenas/mina/gemas.glb')
