/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gemas.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useRef, useMemo, useEffect } from 'react'
import { useFrame } from '@react-three/fiber'
import Brilho from '../../componentes_auxiliares/brilho'
import { Vector3 } from 'three'
import { MathUtils } from 'three'

const Gemas = ({formato = "esmeralda" ,cor = null, gema_index , projeto_escolhido, set_interface , ...props}) => {

  const { nodes, materials } = useGLTF('/modelos_cenas/mina/gemas.glb')

  const cores_hex = {
    vermelho: "#ff4444",
    azul: "#4488ff",
    verde: "#44ff88",
    laranja: "#ff8844",
    roxo: "#aa44ff"
  }
  const material_cores = {
    vermelho : materials['V_01.001'],
    azul : materials['V_02.001'],
    verde : materials['V_03.001'],
    laranja : materials['V_04.001'],
    roxo : materials['V_05.001']

  }
  const formatos = {

    brilhante : {
      roxo : nodes.Gemstone_01.geometry,
      laranja : nodes.Gemstone_01001.geometry,
      verde : nodes.Gemstone_01002.geometry,
      azul : nodes.Gemstone_01003.geometry,
      vermelho : nodes.Gemstone_01004.geometry,      
      rotacao : new Vector3(Math.PI / 90 , Math.PI / 3 , Math.PI / 90 )
    },

    gota : {
      roxo : nodes.Gemstone_02.geometry,
      laranja : nodes.Gemstone_02004.geometry,
      verde : nodes.Gemstone_02003.geometry,
      azul : nodes.Gemstone_02002.geometry,
      vermelho : nodes.Gemstone_02001.geometry,      
      rotacao : new Vector3(Math.PI / 2 ,0 , Math.PI / 15 )
    },

    almofada : {
      roxo : nodes.Gemstone_03.geometry,
      laranja : nodes.Gemstone_03001.geometry,
      verde : nodes.Gemstone_03002.geometry,
      azul : nodes.Gemstone_03003.geometry,
      vermelho : nodes.Gemstone_03004.geometry,      
      rotacao : new Vector3(4 ,5 ,2.5 )
    },

    esmeralda : {
      roxo : nodes.Gemstone_04.geometry,
      laranja : nodes.Gemstone_04001.geometry,
      verde : nodes.Gemstone_04002.geometry,
      azul : nodes.Gemstone_04003.geometry,
      vermelho : nodes.Gemstone_04004.geometry,      
      rotacao : new Vector3(0, Math.PI / 2.5 , Math.PI / 2 )
    },

    trapezio : {
      roxo : nodes.Gemstone_05.geometry,
      laranja : nodes.Gemstone_05001.geometry,
      verde : nodes.Gemstone_05002.geometry,
      azul : nodes.Gemstone_05003.geometry,
      vermelho : nodes.Gemstone_05004.geometry,      
      rotacao : new Vector3(Math.PI / -2 , Math.PI / -4 , Math.PI )
    },
  }

  const atraso = useRef(Math.random() * Math.PI * 2)
  const gema = useRef(null)
  const glow = useRef(null)
  const luz = useRef(null)
  const hover = useRef(0)
  const em_animacao = useRef(false)

  const rotacao_inicial = new Vector3(...props.rotation)
  const rotacao_final = formatos[formato].rotacao
  const rotacao_alvo = useRef(rotacao_inicial)
  const posicao_final = new Vector3(...props.posicao_final)
  const posicao_inicial = new Vector3(...props.posicao_inicial)
  const posicao_alvo = useRef(posicao_inicial)

  useEffect(() => {

    if (projeto_escolhido == gema_index) {

      posicao_alvo.current = posicao_final 
      rotacao_alvo.current = rotacao_final
      em_animacao.current = true

    }else if (projeto_escolhido != gema_index && posicao_final.equals(posicao_alvo.current)) {

      posicao_alvo.current = posicao_inicial 
      rotacao_alvo.current = rotacao_inicial
      em_animacao.current = true
      set_interface(false)

    }
  }, [projeto_escolhido])

  const gerar_formato = (formato_base = null, cor = null) => {

    if (!formato_base){

      const formatos_disponiveis = Object.keys(formatos)

      formato_base = formatos_disponiveis[Math.floor(Math.random() * formatos_disponiveis.length)]

    }

    if (!cor){

      const cores_disponiveis = Object.keys(material_cores)

      cor = cores_disponiveis[Math.floor(Math.random() * cores_disponiveis.length)]

    }

    const formatos_disponiveis = formatos[formato_base]

    return [formatos_disponiveis[cor], cor]

  }

  const [formato_escolhido, cor_escolhida] = gerar_formato(formato, cor)

  const material = useMemo(() => {
    return material_cores[cor_escolhida].clone();
  }, [cor_escolhida])

  useFrame(({clock}) => {

    if (!glow.current || !luz.current) return
    
    const delta = clock.getElapsedTime()

    const animacao_indo = posicao_final.equals(posicao_alvo.current) ? true : false

    const hover_ativo = !em_animacao.current && hover.current == 1 && !animacao_indo? 1 : 0 

    const escala_brilho = Math.sin(delta + atraso.current) * .5 + .9 + hover_ativo

    glow.current.scale.set(escala_brilho, escala_brilho, escala_brilho)

    luz.current.intensity = Math.sin(delta + atraso.current) * .5 + 1.5 + hover_ativo

    if (!em_animacao.current  || !gema.current) return

    gema.current.position.lerp(posicao_alvo.current, .025) 

    const gema_rotacao = gema.current.rotation

    gema_rotacao.x = MathUtils.lerp(gema_rotacao.x, rotacao_alvo.current.x, 0.025)
    gema_rotacao.y = MathUtils.lerp(gema_rotacao.y, rotacao_alvo.current.y, 0.025)
    gema_rotacao.z = MathUtils.lerp(gema_rotacao.z, rotacao_alvo.current.z, 0.025)

    if (gema.current.position.distanceTo(posicao_alvo.current) < 0.01){

      em_animacao.current = false

      if (posicao_final.equals(posicao_alvo.current)) set_interface(true)

    }
  })

  return (
    <group ref={gema} position={props.posicao_inicial} rotation={props.rotation} {...props} dispose={null}>
      
      <mesh 
      geometry={formato_escolhido} 
      material={material}
      onPointerOver={() => {hover.current = 1}}
      onPointerLeave={() => { hover.current = 0 }}
      onPointerDown={() => 
      {posicao_alvo.current = posicao_final 
      em_animacao.current = true}}/>

      <mesh 
        ref={glow}
        raycast={() => null}>

        <sphereGeometry args={[3, 3, 3]} />

        <Brilho
        falloff={.8}
        glowInternalRadius={5.1}
        glowColor={cores_hex[cor_escolhida]}
        glowSharpness={2.3}
        side={"THREE.FrontSide"}
        opacity={.50}
        depthTest={false}
        />
      </mesh>

      <pointLight 
        ref={luz}
        color={cores_hex[cor_escolhida]}
        intensity={10} 
        decay={2} 
        castShadow 
      />

    </group>
  )
}

export default Gemas

useGLTF.preload('/modelos_cenas/mina/gemas.glb')
