/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mina.glb 
*/

import { useState, useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useSpring, animated } from '@react-spring/three'
import { useFrame } from '@react-three/fiber'
import { CatmullRomCurve3, Vector3  } from 'three'

import Interface_mina from './interface_mina'

export default function Mina({proximo_caminho, voltar_caminho , ativado, controle_de_camera, referencia_camera , ...props}) {

  const { nodes, materials } = useGLTF('/models/mina.glb')
  const [interface_ativada, set_interface] = useState(false)
  const [animacao_ativa, set_animacao] = useState("idle")

  const carrinho = useRef(null)

  const animacao_inversa = useRef(false)
  const progresso = useRef(0)

  useEffect(() => {
    
    if (!ativado || !referencia_camera.current) return

    console.log(ativado)

    controle_de_camera.current.desativar_controle()
    set_interface(true)

  }, [ativado])

  const animacoes = {

    carrinho_chega : {
        duracao : .6,

        carrinho : new CatmullRomCurve3([
          new Vector3(-0.026, 0.15, 3),
          new Vector3(-0.026, 0.15, 0)
        ]),

        camera : null,
    },

    camera_para_carrinho : {

        duracao : .6,

        carrinho : null,

        camera : {
          posicao : new CatmullRomCurve3([
            new Vector3(8.30, 3.11, -3.98),
            new Vector3(8.30, 3.11, -3.98),
          ]),
          direcao : new CatmullRomCurve3([
            new Vector3(9.5, 2.4, -2),
            new Vector3(9.5, 2.4, -2)
          ])
        },
    },

    entrando_mina : {

      duracao : .6,

      carrinho : new CatmullRomCurve3([
        new Vector3(-0.026, 0.15, 0),
      ]),
      camera : {

        direcao : new CatmullRomCurve3([

        ]),

        posicao : new CatmullRomCurve3([

        ]),
      }
    }

  }

  useFrame(({clock}) => {

    if (animacao_ativa == "idle" || !carrinho.current || !referencia_camera.current) return

    const proximo_frame = animacao_inversa.current ? 1 - progresso.current : progresso.current 

    progresso.current += clock.getElapsedTime()

    
    {/* ANIMACAO CAMERA */}
    if (animacao_ativa == "carrinho_chega"){
      const camera = referencia_camera.current
      camera.position.lerp(new Vector3(8.30, 3.11, -3.98), 0.08)
      camera.lookAt(new Vector3(9.5, 2.4, -2))
    }

    else if (animacoes[animacao_ativa["camera"]]) {

      const localizacao = animacoes[animacao_ativa]["posicao"].getPoint(proximo_frame)
      
      const direcao = animacoes[animacao_ativa]["direcao"].getPoint(proximo_frame)
      
      referencia_camera.current.lookAt(direcao)

      referencia_camera.current.position.copy(localizacao)
    }

    {/* ANIMACAO CARRINHO */}
    if (animacoes[animacao_ativa["carrinho"]]) {
      
      const posicao = animacoes[animacao_ativa["carrinho"]].getPoint(proximo_frame)

      carrinho.current.position = posicao

    }

  })


  const fechar_seguir_caminho = (cena) => {

    set_animacao("idle")
    set_interface(false)
    proximo_caminho(cena)
    set_interface(false)
    controle_de_camera.current.ativar_controle()

  }

  const fechar_seguir_voltar = (cena) => {

    set_animacao("idle")
    set_interface(false)
    voltar_caminho(cena)
    set_interface(false)
    controle_de_camera.current.ativar_controle()

  }
  

  return (

    <group {...props}>

      {/* modelo 3d */}
      <group dispose={null} 
      
        onPointerDown={() => {

        if (!ativado) return

      }}>

        <mesh geometry={nodes.Mine_Box.geometry} material={materials['Mine1.002']} position={[0.696, 0.109, -0.476]} rotation={[0, -0.851, 0]} />
        
        <mesh geometry={nodes['Mine_Box_(1)'].geometry} material={materials['Mine1.002']} position={[-0.707, 0.109, 0.441]} />
        
        <animated.mesh geometry={nodes.Mine_Cart.geometry} ref={carrinho} material={materials['Mine1.002']} position={[-0.026, 0.15, 3]} rotation={[0, -1.571, 0]} />
        
        <mesh geometry={nodes.Mine_Ore.geometry} material={materials['Mine1.002']} position={[0.746, 0.109, 0.207]} />
        
        <mesh geometry={nodes['Mine_Ore_(1)'].geometry} material={materials['Mine1.002']} position={[-0.686, 0.109, -0.184]} rotation={[Math.PI, -1.554, Math.PI]} />
        
        <mesh geometry={nodes['Mine_Ore_(2)'].geometry} material={materials['Mine1.002']} position={[0.634, 0.109, -1.042]} rotation={[Math.PI, -1.147, Math.PI]} />
        
        <mesh geometry={nodes.Mine_Enter.geometry} material={materials['Mine1.001']} position={[0, 0.026, 2.101]} rotation={[-Math.PI, 0, -Math.PI]} />
        
        <mesh geometry={nodes.Mine_tracks1.geometry} material={materials['Mine1.001']} position={[0, 0.106, 2.111]} rotation={[0, 1.571, 0]} />
        
        <mesh geometry={nodes['Mine_tracks1_(1)'].geometry} material={materials['Mine1.001']} position={[0, 0.106, 0.111]} rotation={[0, 1.571, 0]} />
      
      </group>

      < pointLight position={[0 ,.8, 1.3]} intensity={15} color={"#7c7c7c"} />

      {/* interface */}
      {interface_ativada ?

        <Interface_mina position={[7,2.7,1]}
          proximo_caminho={fechar_seguir_caminho} 
          voltar_caminho={fechar_seguir_voltar} />
        
        :<></>
        
      }

    </group>
  
  )

}

useGLTF.preload('/models/mina.glb')
