/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mina.glb 
*/

import { useState, useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { CatmullRomCurve3, Vector3  } from 'three'

import Interface_mina from './interface_mina'

export default function Mina({proximo_caminho, voltar_caminho , ativado, controle_de_camera, referencia_camera , ...props}) {

  const { nodes, materials } = useGLTF('/models/mina.glb')
  const [interface_ativada, set_interface] = useState(false)
  const [animacao_ativa, set_animacao] = useState("idle")

  const carrinho = useRef(null)
  const animacao_inversa = useRef(false)
  const iluminacao = useRef(15)
  const progresso = useRef(0)
  const avancar_jornada = useRef(null)

  useEffect(() => {
    
    if (!referencia_camera.current) return

    console.log(ativado)

    if (ativado){
      controle_de_camera.current.desativar_controle()
      set_animacao("carrinho_chega")
    }
    else if (animacao_ativa != "idle") {
      voltar_idle()
    }
    

  }, [ativado])

  const animacoes = {

    carrinho_chega : {
        duracao : 2,

        carrinho : new CatmullRomCurve3([
          new Vector3(-0.026, 0.15, 3),
          new Vector3(-0.026, 0.15, 0)
        ]),

        camera : null,
    },

    camera_para_carrinho : {

        duracao : 3,

        carrinho : null,

        camera : {
          posicao : new CatmullRomCurve3([
            new Vector3(8.30, 3.11, -3.98),
            new Vector3(9.2, 2.8, -3.4),
          ]),
          direcao : new CatmullRomCurve3([
            new Vector3(9.5, 2.4, -2),
            new Vector3(9.2, 2.4, 5)
          ])
        },
    },

    entrando_mina : {

      duracao : 3,

      carrinho : new CatmullRomCurve3([
        new Vector3(-0.026, 0.15, 0),
        new Vector3(-0.026, 0.15, 1.65),
      ]),
      camera : {

        posicao : new CatmullRomCurve3([
          new Vector3(9.2, 2.8, -3.4),
          new Vector3(9.2, 2.8, -1.4)
        ]),

        direcao : new CatmullRomCurve3([
          new Vector3(9.2, 2.4, 5),
          new Vector3(9.2, 2.4, 5)
        ]),
      }
    }
  }

  const animacoes_nome = [
    "idle",
    "carrinho_chega",
    "camera_para_carrinho",
    "entrando_mina",
    "finalizado",
  ]

  useFrame((state, delta) => {

    if (animacao_ativa == "idle" || animacao_ativa == "finalizado" || !carrinho.current || !referencia_camera.current) return

    progresso.current += delta

    const inverter_animacao = animacao_inversa.current == 1 ? 1 : 0 

    const tempo_atual = inverter_animacao ? 1 - Math.min(progresso.current / animacoes[animacao_ativa].duracao, 1)
    : Math.min(progresso.current / animacoes[animacao_ativa].duracao, 1)

    console.log(tempo_atual)
    
    {/* ANIMACAO CAMERA */}
    if (animacao_ativa == "carrinho_chega"){
      const camera = referencia_camera.current
      camera.position.lerp(new Vector3(8.30, 3.11, -3.98), 0.1)
      camera.lookAt(new Vector3(9.5, 2.4, -2))
    }

    else if (animacoes[animacao_ativa]["camera"]) {

      const localizacao = animacoes[animacao_ativa]["camera"]["posicao"].getPoint(tempo_atual)
      
      const direcao = animacoes[animacao_ativa]["camera"]["direcao"].getPoint(tempo_atual)
      
      referencia_camera.current.lookAt(direcao)

      referencia_camera.current.position.copy(localizacao)
    }

    {/* ANIMACAO CARRINHO */}
    if (animacoes[animacao_ativa]["carrinho"]) {
      
      const posicao = animacoes[animacao_ativa]["carrinho"].getPoint(tempo_atual)

      carrinho.current.position.copy(posicao)

    }

    if (tempo_atual >= 1 || tempo_atual <= 0 && inverter_animacao){

      if (animacao_ativa == "entrando_mina" && !inverter_animacao){
        set_interface(true)
        iluminacao.current = 0
      }

      if (animacao_ativa == "carrinho_chega" && inverter_animacao){

        if (proximo_caminho.current) proximo_caminho("mina") 
        else voltar_caminho("mina")
        
        voltar_idle()

        return

      }

      const animacao_escolhida = animacoes_nome[animacoes_nome.indexOf(animacao_ativa) + 1 - animacao_inversa.current * 2]

      set_animacao(animacao_escolhida)

      progresso.current = 0

    }

  })

  const fechar_seguir_caminho = () => {

    set_interface(false)
    avancar_jornada.current = true
    animacao_inversa.current = 1
    progresso.current = 0
    set_animacao(animacoes_nome[animacoes_nome.indexOf(animacao_ativa) - 1])

  }

  const fechar_voltar_caminho = () => {

    set_interface(false)
    avancar_jornada.current = false
    animacao_inversa.current = 1
    progresso.current = 0
    set_animacao(animacoes_nome[animacoes_nome.indexOf(animacao_ativa) + - 1])

  }

  const voltar_idle = () => {
    set_animacao("idle")
    set_interface(false)
    controle_de_camera.current.ativar_controle()
    progresso.current = 0
    iluminacao.current = 1
    animacao_inversa.current = 0

  }
  

  return (

    <group {...props}>

      {/* modelo 3d */}
      <group dispose={null} 
      
        onPointerDown={() => {

        if (!ativado) return

      }}>

        <mesh geometry={nodes.Mine_Box.geometry} material={materials['Mine1.002']} position={[0.696, 0.109, -0.476]} rotation={[0, -0.851, 0]} />
        
        <mesh geometry={nodes['Mine_Box_(1)'].geometry} material={materials['Mine1.002']} position={[-0.707, 0.109, 0.441]} />
        
        <mesh geometry={nodes.Mine_Cart.geometry} ref={carrinho} material={materials['Mine1.002']} position={[-0.026, 0.15, 3]} rotation={[0, -1.571, 0]} />
        
        <mesh geometry={nodes.Mine_Ore.geometry} material={materials['Mine1.002']} position={[0.746, 0.109, 0.207]} />
        
        <mesh geometry={nodes['Mine_Ore_(1)'].geometry} material={materials['Mine1.002']} position={[-0.686, 0.109, -0.184]} rotation={[Math.PI, -1.554, Math.PI]} />
        
        <mesh geometry={nodes['Mine_Ore_(2)'].geometry} material={materials['Mine1.002']} position={[0.634, 0.109, -1.042]} rotation={[Math.PI, -1.147, Math.PI]} />
        
        <mesh geometry={nodes.Mine_Enter.geometry} material={materials['Mine1.001']} position={[0, 0.026, 2.101]} rotation={[-Math.PI, 0, -Math.PI]} />
        
        <mesh geometry={nodes.Mine_tracks1.geometry} material={materials['Mine1.001']} position={[0, 0.106, 2.111]} rotation={[0, 1.571, 0]} />
        
        <mesh geometry={nodes['Mine_tracks1_(1)'].geometry} material={materials['Mine1.001']} position={[0, 0.106, 0.111]} rotation={[0, 1.571, 0]} />
      
      </group>

      < pointLight position={[0 ,.8, 1.3]} intensity={iluminacao.current} color={"#7c7c7c"} />

      {/* interface */}
      {interface_ativada ?

        <Interface_mina position={[5,3.09,5]}
        proximo_caminho={fechar_seguir_caminho} 
        voltar_caminho={fechar_voltar_caminho} />
        
        :<></>
        
      }

    </group>
  
  )

}

useGLTF.preload('/models/mina.glb')
