/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 parede.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Parede(props) {
  const { nodes, materials } = useGLTF('/modelos_cenas/mina/parede.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Stone} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Stone} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Stone} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Stone} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Material.010']} />
      </group>
    </group>
  )
}

useGLTF.preload('/modelos_cenas/mina/parede.glb')
