/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 acampamento.glb 
*/

import { useState, useRef } from 'react'

import { useGLTF, Text3D  } from '@react-three/drei'

import { VFXEmitter , VFXParticles } from "wawa-vfx"

import Interface_acampamento from './interface_acampamento'

export default function Acampamento({proximo_caminho, voltar_camimho , ...props}) {

  const [fogueira_ativa, set_fogueira_ativa] = useState(false)

  const [interface_ativa, set_interface_ativa] = useState(false)

  const { nodes, materials } = useGLTF('/models/acampamento.glb')

  const fogueira_posicao = [-0.179, 0.112, -1.14]

  const emissor_particulas = useRef(null)

  function trocar_particulas(bool) {

    if (bool) {

      emissor_particulas.current.startEmitting()

    }

    else{

      emissor_particulas.current.stopEmitting()

    }
  }

  function ativar_acampamento () {

    set_fogueira_ativa(true)

    trocar_particulas(fogueira_ativa)

    set_interface_ativa(true)

    proximo_caminho("acampamento")

  }

  function desativar_acampamento() {

    set_fogueira_ativa(false)

    set_interface_ativa(false)

    trocar_particulas(fogueira_ativa)

    proximo_caminho(null)

  }


  return (
    
    <group {...props}>

      {/*modelo 3d*/}
      <group dispose={null} onPointerUp={(e) => {
        
          if (fogueira_ativa) {

            desativar_acampamento()

          }

          else{

            ativar_acampamento()

          }

          set_fogueira_ativa(!fogueira_ativa) 
          
        }}
        
      >

        <mesh geometry={nodes.Bench2.geometry} material={materials['props.006']} position={[1.467, 0.112, -0.43]} rotation={[Math.PI, -0.833, Math.PI]} />

        <mesh geometry={nodes.Bucket.geometry} material={materials['props.006']} position={[1.161, 0.112, 0.747]} rotation={[Math.PI, -1.566, Math.PI]} />



        <mesh geometry={nodes.Camp2_Fierplace1.geometry} material={materials['camp_02.002']} position={fogueira_posicao} rotation={[Math.PI, -1.566, Math.PI]} />

        <mesh geometry={nodes.Camp2_tent.geometry} material={materials['camp_02.002']} position={[-0.158, 0.112, 0.48]} rotation={[Math.PI, -0.781, Math.PI]} scale={[1, 1, 1.279]} />
        
        <mesh geometry={nodes.Chest1B.geometry} material={materials['chests.004']} position={[1.817, 0.112, 1.119]} rotation={[Math.PI, -0.14, Math.PI]} />

        <mesh geometry={nodes.Chest1B001.geometry} material={materials['chests.001']} position={[1.817, 0.461, 1.119]} rotation={[Math.PI, -0.675, Math.PI]} />

        <VFXParticles 
              name="fire"
              
              settings={{
                nbParticles: 1000,
                gravity: [0, 2, -2],
                renderMode: 'billboard',
                }
              }
        />
            
        <VFXEmitter 

              ref={emissor_particulas}

              emitter="fire"

              settings={{
                
                loop:true,

                velocity: {
                  direction: [0, 1, 0],
                  spread: 0.5,
                  speed: [1, 3]
                },

                size: [0.02, 0.1],

                spawnMode: "continuous",

                duration: 2,

                position : {fogueira_posicao},

                startPositionMin: fogueira_posicao.map((valor) => valor - .4),

                startPositionMax: fogueira_posicao.map((valor) => valor + .4),

                nbParticles: 90,

                lifetime: [0.5, 1.5],

                colorStart: ['#ff6b35', '#f7931e'],

                colorEnd: ['#ff0000', '#8b0000'],

            }}
        />

      </group>

      {/*interface*/}

      {interface_ativa ? 
        <Interface_acampamento position={[0,1,0]}/> 
        
        : <></>
      }

    </group>

  )

}

useGLTF.preload('/models/acampamento.glb')
