/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pocao.glb 
*/

import { useMemo } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pocao({quantidade_liquido, cor , ...props}) {

  const { nodes, materials } = useGLTF('/modelos_cenas/acampamento/pocao.glb')

  const liquido = useMemo(() => {
    
    if (!materials.Material_0) return null;
    const mat = materials.Material_0.clone();
    
    // Aplica a cor desejada. No Three.js, se o material já tem uma textura (map),
    // a propriedade 'color' automaticamente funciona como um "tingimento" (multiplicador de cor)
    // mantendo os detalhes de sombra e relevo da textura em grayscale.
    mat.color.set(cor); 
    
    return mat;
  }, [materials.Material_0]);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cuboid.geometry} material={liquido} position={[0, 0.625, 0]} />
      <mesh geometry={nodes.cuboid001.geometry} material={liquido} position={[0, 0.625, 0]} />
      <mesh geometry={nodes.cuboid002.geometry} material={liquido} position={[0, 0.625, 0]} />
      <mesh geometry={nodes.cuboid003.geometry} material={liquido} position={[0, 0.625, 0]} />
      <mesh geometry={nodes.cuboid004.geometry} material={liquido} position={[0, 0.625, 0]} />
      <mesh geometry={nodes.cuboid005.geometry} material={liquido} position={[0, 0.625, 0]} />
      <mesh geometry={nodes.cuboid006.geometry} material={liquido} position={[0, 0.625, 0]} />
      <mesh geometry={nodes.cuboid007.geometry} material={liquido} position={[0, 0.625, 0]} />
      <mesh geometry={nodes.cuboid008.geometry} material={liquido} position={[0, 0.625, 0]} />
      <mesh geometry={nodes.cuboid009.geometry} material={materials.Material_0} position={[0, 0.625, 0]} />
      <mesh geometry={nodes.glass1.geometry} material={materials.Material_1} position={[0.199, 0.625, -0.063]} scale={[0.187, 1, 1]} />
      <mesh geometry={nodes.glass3.geometry} material={materials.Material_1} position={[-0.375, 0.625, -0.275]} scale={[1, 1, 0.164]} />
      <mesh geometry={nodes.glass4.geometry} material={materials.Material_1} position={[-0.375, 0.625, 0.205]} scale={[1, 1, 0.147]} />
      <mesh geometry={nodes.cuboid010.geometry} material={liquido} position={[0, 0.625, 0]} />
      <mesh geometry={nodes.cuboid011.geometry} material={liquido} position={[0, 0.625, 0]} />
      <mesh geometry={nodes.glass2.geometry} material={materials.Material_1} position={[-0.253, 0.625, -0.063]} scale={[0.046, 1, 1]} />
      
      {/* LIQUIDO */}
      <mesh geometry={nodes.liquid.geometry} material={liquido}
        position={[0, 0.43 * quantidade_liquido + 0.38, 0]}
        scale={[1, quantidade_liquido * 2, 1]} />

    </group>
  )
}

useGLTF.preload('/modelos_cenas/acampamento/pocao.glb')
