/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 porta.glb 
*/

import { useRef } from 'react'

import { useSpring, animated } from '@react-spring/three'

import { useGLTF } from '@react-three/drei'

import Texto_3d from '../../componentes_auxiliares/texto_3d'

export default function Porta({proximo_caminho, voltar_caminho, ativado, ...props}) {

  const { nodes, materials } = useGLTF('/models/porta.glb')

  const porta = useRef(null)

  const fechar = ( ) => {

    if (porta.current){

      proximo_caminho("porta")

    }

  }

  const abrir = ( ) => {

    if ( porta.current ) {

      proximo_caminho("porta")

    }

  }

  //animação da porta
  const { rotation } = useSpring(

    {

      rotation: ativado ? [-Math.PI, -1.2 , -Math.PI] : [-Math.PI, 0, -Math.PI],
      
      config: { tension: 40, friction: 20 }
  
    }

  )

  return (

    <group {...props} >

      <Texto_3d
      texto="testando 123"
      position={[0,0,0]}
      />

      {/* modelo 3d */}
      <group 
      
      dispose={null}

      onPointerDown={ () => {

          if (!ativado) return
          
          fechar()
        
      }}

      >

        <mesh 
          geometry={nodes.doorway.geometry} 
          material={materials['Dungeon_passage.001']} 
          position={[0.019, -0.084, 0.079]} 
          rotation={[-Math.PI, 0, -Math.PI]} 
        />

        <animated.group
          ref={porta}
          position={[ .52, -.09 , 0 ]}
          rotation={rotation}
        >
          
          <mesh 
            geometry={nodes.door.geometry} 
            material={materials['Dungeon_passage.002']} 
            position={[ .5, 0, 0 ]}
          />

        </animated.group>

      </group>

    </group>

  )

}

useGLTF.preload('/models/porta.glb')
