/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 porta.glb 
*/

import { useRef, useState } from 'react'

import { useSpring, animated } from '@react-spring/three'

import { useGLTF } from '@react-three/drei'

export default function Porta(props) {

  const { nodes, materials } = useGLTF('/models/porta.glb')

  const porta = useRef(null)

  const [ aberta , setAberta] = useState(false)

  const fechar = ( ) => {

    if (porta.current){

      setAberta(false)

    }

  }

  const abrir = ( ) => {

    if ( porta.current ) {

      setAberta(true)

    }

  }

  //animação da porta
  const { rotation } = useSpring(

    {

      rotation: aberta ? [-Math.PI, -1.2 , -Math.PI] : [-Math.PI, 0, -Math.PI],
      
      config: { tension: 40, friction: 20 }
  
    }

  )

  return (

    <group 
    
    {...props} 
    
    dispose={null}

    onPointerOver={ () => abrir() }

    onPointerOut={ () => fechar() }

    >

      <mesh 
      
        geometry={nodes.doorway.geometry} 
        
        material={materials['Dungeon_passage.001']} 
        
        position={[0.019, -0.084, 0.079]} 
        
        rotation={[-Math.PI, 0, -Math.PI]} 
      
      />

      <animated.group

        ref={porta}

        position={[ .515, -.09 , 0 ]}

        rotation={rotation}
      >
        
        <mesh 

          geometry={nodes.door.geometry} 

          material={materials['Dungeon_passage.002']} 

          position={[ .5, 0, 0 ]}

        />

      </animated.group>

    </group>

  )

}

useGLTF.preload('/models/porta.glb')
