/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 csharp-icon.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Csharp_icon(props) {
  const { nodes, materials } = useGLTF('/modelos_cenas/orbe/csharp-icon.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node1.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Node2.geometry} material={materials.Material} />
      <mesh geometry={nodes.Node3.geometry} material={materials.Material} />
      <mesh geometry={nodes.Node4.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node5.geometry} material={materials.x1} />
    </group>
  )
}

useGLTF.preload('/modelos_cenas/orbe/csharp-icon.glb')
