/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 csharp.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Modelo_csharp(props) {
  const { nodes, materials } = useGLTF('/modelos_cenas/orbe/csharp.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['C#'].geometry} material={materials.material} position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.002} />
    </group>
  )
}

useGLTF.preload('/modelos_cenas/orbe/csharp.glb')
