/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 css.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Modelo_css(props) {
  const { nodes, materials } = useGLTF('/modelos_cenas/orbe/css.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.129, 0]}>
        <mesh geometry={nodes.CSSsvg.geometry} material={materials.blue} />
        <mesh geometry={nodes.CSSsvg_1.geometry} material={materials.white} />
        <mesh geometry={nodes.CSSsvg_2.geometry} material={materials.gray} />
      </group>
    </group>
  )
}

useGLTF.preload('/modelos_cenas/orbe/css.glb')
