/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 html.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Modelo_html(props) {
  const { nodes, materials } = useGLTF('/modelos_cenas/orbe/html.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.164, -0.089, -0.006]}>
        <mesh geometry={nodes.HTMLsvg001_1.geometry} material={materials.orange} />
        <mesh geometry={nodes.HTMLsvg001_2.geometry} material={materials['white.002']} />
        <mesh geometry={nodes.HTMLsvg001_3.geometry} material={materials['gray.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/modelos_cenas/orbe/html.glb')
