/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 html5-icon.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Html5_icon(props) {
  const { nodes, materials } = useGLTF('/modelos_cenas/orbe/html5-icon.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node1.geometry} material={materials['x1.002']} />
      <mesh geometry={nodes.Node10.geometry} material={materials['x1.002']} />
      <mesh geometry={nodes.Node11.geometry} material={materials['x1.002']} />
      <mesh geometry={nodes.Node12.geometry} material={materials['x1.002']} />
      <mesh geometry={nodes.Node13.geometry} material={materials['x1.002']} />
      <mesh geometry={nodes.Node14.geometry} material={materials['x1.002']} />
      <mesh geometry={nodes.Node15.geometry} material={materials['x1.002']} />
      <mesh geometry={nodes.Node16.geometry} material={materials['x1.002']} />
      <mesh geometry={nodes.Node17.geometry} material={materials['x1.002']} />
      <mesh geometry={nodes.Node18.geometry} material={materials['x1.002']} />
      <mesh geometry={nodes.Node19.geometry} material={materials['x1.002']} />
      <mesh geometry={nodes.Node2.geometry} material={materials.Material} />
      <mesh geometry={nodes.Node3.geometry} material={materials['x1.002']} />
      <mesh geometry={nodes.Node4.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Node5.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Node6.geometry} material={nodes.Node6.material} />
      <mesh geometry={nodes.Node7.geometry} material={nodes.Node7.material} />
      <mesh geometry={nodes.Node8.geometry} material={materials['x1.002']} />
      <mesh geometry={nodes.Node9.geometry} material={materials['x1.002']} />
    </group>
  )
}

useGLTF.preload('/modelos_cenas/orbe/html5-icon.glb')
