/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 javascript.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Modelo_javascript(props) {
  const { nodes, materials } = useGLTF('/modelos_cenas/orbe/javascript.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.139, 0, 0]}>
        <mesh geometry={nodes.Mesh001.geometry} material={materials.yellow} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={materials.black} />
      </group>
    </group>
  )
}

useGLTF.preload('/modelos_cenas/orbe/javascript.glb')
