/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 python-icon.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import Brilho from "../../../componentes_auxiliares/brilho.jsx"

export function Python_icon(props) {
  const { nodes, materials } = useGLTF('/modelos_cenas/orbe/python-icon.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node1.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Node2.geometry} material={materials['x1.001']} />
      <mesh geometry={nodes.Node3.geometry} material={materials['x1.001']} />
      <mesh geometry={nodes.Node4.geometry} material={materials['x1.001']} />
      <mesh geometry={nodes.Node5.geometry} material={materials['x1.001']} />
      <mesh geometry={nodes.Node6.geometry} material={materials['x1.001']} />
      <mesh geometry={nodes.Node7.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/modelos_cenas/orbe/python-icon.glb')
