/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 acampamento.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Acampamento(props) {

  const { nodes, materials } = useGLTF('/models/acampamento.glb')

  return (

    <group {...props} dispose={null}>

      <mesh geometry={nodes.Bench2.geometry} material={materials['props.006']} position={[1.467, 0.112, -0.43]} rotation={[Math.PI, -0.833, Math.PI]} />

      <mesh geometry={nodes.Bucket.geometry} material={materials['props.006']} position={[1.161, 0.112, 0.747]} rotation={[Math.PI, -1.566, Math.PI]} />

      <mesh geometry={nodes.Camp2_Fierplace1.geometry} material={materials['camp_02.002']} position={[-0.179, 0.112, -1.14]} rotation={[Math.PI, -1.566, Math.PI]} />

      <mesh geometry={nodes.Camp2_tent.geometry} material={materials['camp_02.002']} position={[-0.158, 0.112, 0.48]} rotation={[Math.PI, -0.781, Math.PI]} scale={[1, 1, 1.279]} />
      
      <mesh geometry={nodes.Chest1B.geometry} material={materials['chests.004']} position={[1.817, 0.112, 1.119]} rotation={[Math.PI, -0.14, Math.PI]} />

      <mesh geometry={nodes.Chest1B001.geometry} material={materials['chests.001']} position={[1.817, 0.461, 1.119]} rotation={[Math.PI, -0.675, Math.PI]} />

    </group>

  )

}

useGLTF.preload('/models/acampamento.glb')
