/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bauDoTesouro.glb 
*/

import { useRef, useState } from 'react'

import { useGLTF } from '@react-three/drei'

import { useSpring, animated } from '@react-spring/three'

export default function BauDoTesouro(props) {

  const { nodes, materials } = useGLTF('/models/bauDoTesouro.glb')

  const tampa = useRef(null)

  const [aberto, setAberto] = useState(false)

  //animação da tampa do bau
  const { rotation } = useSpring(

    {

      rotation: aberto ? [-1, 0, 0] : [1.6, 0, 0],
      
      config: { tension: 120, friction: 14 }
  
    }

  )

  const fechar = ( ) => {

    if (tampa.current){

      setAberto(false)

    }

  }

  const abrir = ( ) => {

    if ( tampa.current ) {

      setAberto(true)

    }

  }

  return (

    <group {...props} dispose={null}
    
      onPointerOver={ () => abrir() }

      onPointerOut={ () => fechar() }

    >

      <mesh 
      
        geometry={nodes.Box.geometry} 
        
        material={materials.chests} 
        
      />

      <mesh 
      
        geometry={nodes.Gold.geometry} 
        
        material={materials.chests} position={[0, 0.379, 0]} 
      
      />

      <animated.mesh 

        ref={tampa}

        geometry={nodes.Lid.geometry} 

        material={materials.chests} 

        rotation= { rotation }
        
        position={[-0.172, 0.429, -0.285]} 

      />

    </group>

  )
  
}

useGLTF.preload('/models/bauDoTesouro.glb')
