/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bauDoTesouro.glb 
*/

import { useRef, useState } from 'react'

import { useGLTF } from '@react-three/drei'

import { useSpring, animated } from '@react-spring/three'

import { Html } from '@react-three/drei'

export default function BauDoTesouro(props) {

  const { nodes, materials } = useGLTF('/models/bauDoTesouro.glb')

  const posicaoGlobal = props.position

  const rotacaoGlobal = props.rotation

  const tampa = useRef(null)

  const [aberto, setAberto] = useState(false)

  //animação da tampa do bau
  const { rotacaoTampa } = useSpring({

      rotacaoTampa: aberto ? [-1.3, 0, 0] : [1.6, 0, 0],
      
      config: { tension: 120, friction: 14 }
  
  })

  //animação do bau
  const { bauEscala , bauRotacao , bauPosicao } = useSpring({

    bauRotacao: aberto ? [0.8, 0, 0.4] : [0, 0, 0],

    bauEscala : aberto ? [1.5, 1.5, 1.5] : [1, 1, 1],

    bauPosicao : aberto ? [0, .3, 0] : [0, 0, 0],
      
    config: { tension: 120, friction: 14 }

  })

  const fechar = ( ) => {

    if (tampa.current){

      setAberto(false)

    }

  }

  const abrir = ( ) => {

    if ( tampa.current ) {

      setAberto(true)

    }

  }

  return (

    <group position={posicaoGlobal} rotation={rotacaoGlobal}>
      
      {/* bau */}
      <animated.group

        rotation={bauRotacao}
      
        position={bauPosicao} 

        scale={bauEscala}
      
        dispose={null}
      
        onPointerOver={ () => abrir() }

        onPointerOut={ () => fechar() }

      >

        <mesh 
        
          geometry={nodes.Box.geometry} 
          
          material={materials.chests} 
          
        />

        <mesh 
        
          geometry={nodes.Gold.geometry} 
          
          material={materials.chests} position={[0, 0.379, 0]} 
        
        />

        <animated.mesh 

          ref={tampa}

          geometry={nodes.Lid.geometry} 

          material={materials.chests} 

          rotation = { rotacaoTampa }
          
          position={[-0.172, 0.429, -0.285]} 

        />

      </animated.group>

    </group>

  )
  
}

useGLTF.preload('/models/bauDoTesouro.glb')
