/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bauDoTesouro.glb 
*/

import React from 'react'

import { useGLTF } from '@react-three/drei'

export default function BauDoTesouro(props) {

  const { nodes, materials } = useGLTF('/models/bauDoTesouro.glb')

  return (

    <group {...props} dispose={null}>

      <mesh geometry={nodes.Box.geometry} material={materials.chests} />

      <mesh geometry={nodes.Gold.geometry} material={materials.chests} position={[0, 0.379, 0]} />

      <mesh geometry={nodes.Lid.geometry} material={materials.chests} position={[-0.172, 0.429, -0.285]} />

    </group>

  )
  
}

useGLTF.preload('/models/bauDoTesouro.glb')
