/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mina.glb 
*/

import { useState, useRef } from 'react'

import { useGLTF } from '@react-three/drei'

import { useSpring, animated } from '@react-spring/three'

export default function CarrinhoDaMina(props) {

  const posicaoGlobal = props.position

  const [ativo, setAtivo] = useState(false)

  const { posicaoCarrinho } = useSpring({

    posicaoCarrinho : ativo ? [-0.026, 0.059, 0] : [-0.026, 0.059, 3],

    config: { tension: 40, friction: 20 }
    
  })

  const carrinho = useRef(null)

  const { nodes, materials } = useGLTF('/models/carrinhoDaMina.glb')

  return (

    <group {...props} dispose={null} onPointerUp={() => setAtivo(!ativo)}>

      <mesh geometry={nodes.Mine_Box.geometry} material={materials['Mine1.002']} position={[0.515, 0.003, -0.476]} rotation={[0, -0.851, 0]} />

      <mesh geometry={nodes['Mine_Box_(1)'].geometry} material={materials['Mine1.002']} position={[-0.584, 0.003, 0.441]} />
      
      <animated.mesh geometry={nodes.Mine_Cart.geometry} ref={carrinho} material={materials['Mine1.002']} position={posicaoCarrinho} rotation={[0, -1.571, 0]} />
      
      <mesh geometry={nodes.Mine_Ore.geometry} material={materials['Mine1.002']} position={[0.565, 0.003, 0.207]} />
      
      <mesh geometry={nodes['Mine_Ore_(1)'].geometry} material={materials['Mine1.002']} position={[-0.563, 0.003, -0.184]} rotation={[Math.PI, -1.554, Math.PI]} />
      
      <mesh geometry={nodes['Mine_Ore_(2)'].geometry} material={materials['Mine1.002']} position={[0.453, 0.003, -1.042]} rotation={[Math.PI, -1.147, Math.PI]} />
    
    </group>
  
  )

}

useGLTF.preload('/models/carrinhoDaMina.glb')
