/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 orbe.glb 
*/

import React from 'react'

import { useGLTF } from '@react-three/drei'

export default function Orbe(props) {

  const { nodes, materials } = useGLTF('/models/orbe.glb')

  return (

    <group {...props} dispose={null}>

      <mesh geometry={nodes.Magic_Shrine1.geometry} material={materials['Magic_Pillars.002']} position={[-0.025, 0.024, -0.005]}>

        <mesh geometry={nodes.Magic_Orb002.geometry} material={materials['Magic_Orb 1.002']} position={[0, 1.37, 0]} rotation={[-1.685, -0.078, -1.964]} />

      </mesh>

    </group>

  )

}

useGLTF.preload('/models/orbe.glb')
