/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 porta.glb 
*/

import React from 'react'

import { useGLTF } from '@react-three/drei'

export default function Porta(props) {

  const { nodes, materials } = useGLTF('/models/porta.glb')

  return (

    <group {...props} dispose={null}>

      <mesh geometry={nodes.doorway.geometry} material={materials['Dungeon_passage.001']} position={[0.019, -0.084, 0.079]} rotation={[-Math.PI, 0, -Math.PI]} />

      <mesh geometry={nodes.door.geometry} material={materials['Dungeon_passage.002']} position={[0.019, -0.084, 0.079]} rotation={[-Math.PI, 0, -Math.PI]} />

    </group>

  )

}

useGLTF.preload('/models/porta.glb')
