/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 orbe.glb 
*/

import { useRef, useState, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from "three";
import { useSpring, animated } from '@react-spring/three'
import { Effect } from 'postprocessing';

export default function Orbe({ ativado, set_interface , ...props}) {

  const referenciaOrbe = useRef(null)
  const [orbe_ativa, set_ativa] = useState(false)

  const { nodes, materials } = useGLTF('/models/orbe.glb')

  const {esfera_tamanho} = useSpring({

    esfera_tamanho : orbe_ativa ? [1 ,1 ,1] : [0 ,0 ,0],

    config: { tension: 80, friction: 20 },

  })

  useFrame( ({clock}) => {

    const delta = clock.getElapsedTime()

    if (referenciaOrbe.current && !orbe_ativa) {

      referenciaOrbe.current.rotation.z = delta * 2

      referenciaOrbe.current.rotation.y = delta * 2

      referenciaOrbe.current.position.y = Math.sin(delta) * 0.15 + 1.4

    }

    }

  )

  useEffect(() => {

    set_ativa(ativado)

  },[ativado])

  return (

    <group {...props} dispose={null}>

      <mesh 

        onPointerDown={ () => {

          if (!ativado) return
        
        }}

        geometry={nodes.Magic_Shrine1.geometry} 
      
        material={materials['Magic_Pillars.002']} 
        
        position={[-0.025, 0.024, -0.005]}>

        <mesh 

          ref={referenciaOrbe}
        
          geometry={nodes.Magic_Orb002.geometry} 
          
          material={materials['Magic_Orb 1.002']} 
          
          position={[0, 1.37, 0]} 

          rotation={[-1.685, -0.078, -1.964]} 
          
        />

      </mesh>

      <animated.mesh scale={esfera_tamanho} position={[ 0, 1.37, 0]}>
        <sphereGeometry args={[ 1.88 , 8, 8]} />

        <meshBasicMaterial 
            color={"black"}
            side={THREE.DoubleSide}
        />
      </animated.mesh>

      < pointLight position={[0, 1, 0]} intensity={10} color={"#6f0079"} />



    </group>

  )

}

useGLTF.preload('/models/orbe.glb')
