/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bauDoTesouro.glb 
*/

import { useRef, useState } from 'react'

import { useGLTF } from '@react-three/drei'

import { useSpring, animated } from '@react-spring/three'

import Interface_bau from './interface_bau'

export default function BauDoTesouro({ proximo_camimho, voltar_caminho, ativado , ...props}) {

  const { nodes, materials } = useGLTF('/models/bauDoTesouro.glb')

  const tampa = useRef(null)

  const abrir = () => {

    voltar_caminho("bau")

  }

  const fechar = () => {

    voltar_caminho("bau")

  }

  //animação da tampa do bau
  const { rotacaoTampa } = useSpring({

      rotacaoTampa: ativado ? [-1.3, 0, 0] : [1.6, 0, 0],
      
      config: { tension: 120, friction: 14 }
  
  })

  //animação do bau
  const { bauEscala , bauRotacao , bauPosicao } = useSpring({

    bauRotacao: ativado ? [0.8, 0, 0] : [0, .1, 0],

    bauEscala : ativado ? [1.8, 1.8, 1.8] : [1, 1, 1],

    bauPosicao : ativado ? [.1, .2, .3] : [0, 0, 0],
      
    config: { tension: 120, friction: 14 }

  })

  return (

    <group {...props} >
      
      {/* bau */}
      <animated.group

        rotation={bauRotacao}
      
        position={bauPosicao} 

        scale={bauEscala}
      
        dispose={null}
      
        onPointerDown={ () => {

          if (!ativado) return       
        
        } }

      >

        <mesh 
        
          geometry={nodes.Box.geometry} 
          
          material={materials.chests} 
          
        />

        <mesh 
        
          geometry={nodes.Gold.geometry} 
          
          material={materials.chests} position={[0, 0.379, 0]} 
        
        />       

        <animated.mesh 

          ref={tampa}

          geometry={nodes.Lid.geometry} 

          material={materials.chests} 

          rotation = { rotacaoTampa }
          
          position={[-0.172, 0.429, -0.285]} 

        />

      </animated.group>

      {ativado ? 
      
        <Interface_bau position={[-1.5, 1.9, .5]}/>
        
        : <></>
      }
      

    </group>

  )
  
}

useGLTF.preload('/models/bauDoTesouro.glb')
