/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bauDoTesouro.glb 
*/

import { useRef, useState } from 'react'

import { useGLTF } from '@react-three/drei'

import { useSpring, animated } from '@react-spring/three'

import Interface_bau from './interface_bau'

export default function BauDoTesouro({ proximo_camimho, voltar_caminho , ...props}) {

  const { nodes, materials } = useGLTF('/models/bauDoTesouro.glb')

  const [aberto, set_aberto] = useState(false)

  const [interface_ativa, set_interface_ativa] = useState(false)

  const posicao_global = props.position

  const rotacao_global = props.rotation

  const tampa = useRef(null)


  //animação da tampa do bau
  const { rotacaoTampa } = useSpring({

      rotacaoTampa: aberto ? [-1.3, 0, 0] : [1.6, 0, 0],
      
      config: { tension: 120, friction: 14 }
  
  })

  //animação do bau
  const { bauEscala , bauRotacao , bauPosicao } = useSpring({

    bauRotacao: aberto ? [0.8, 0, 0] : [0, .1, 0],

    bauEscala : aberto ? [1.8, 1.8, 1.8] : [1, 1, 1],

    bauPosicao : aberto ? [.1, .2, .3] : [0, 0, 0],
      
    config: { tension: 120, friction: 14 }

  })

  const fechar = ( ) => {

    if (tampa.current){

      set_aberto(false)

      set_interface_ativa(false)

       proximo_camimho, voltar_caminho(null)

    }

  }

  const abrir = ( ) => {

    if ( tampa.current ) {

      set_aberto(true)

      set_interface_ativa(true)

       proximo_camimho, voltar_caminho("bau")

    }

  }

  return (

    <group position={posicao_global} rotation={rotacao_global}>
      
      {/* bau */}
      <animated.group

        rotation={bauRotacao}
      
        position={bauPosicao} 

        scale={bauEscala}
      
        dispose={null}
      
        onPointerDown={ () => {
          
          if (aberto) {
            fechar()
          }
          else {
            abrir()
          }
          
        
        } }

      >

        <mesh 
        
          geometry={nodes.Box.geometry} 
          
          material={materials.chests} 
          
        />

        <mesh 
        
          geometry={nodes.Gold.geometry} 
          
          material={materials.chests} position={[0, 0.379, 0]} 
        
        />       

        <animated.mesh 

          ref={tampa}

          geometry={nodes.Lid.geometry} 

          material={materials.chests} 

          rotation = { rotacaoTampa }
          
          position={[-0.172, 0.429, -0.285]} 

        />

      </animated.group>

      {interface_ativa ? 
      
        <Interface_bau position={[-1.5, 2,0]}/>
        
        : <></>
      }
      

    </group>

  )
  
}

useGLTF.preload('/models/bauDoTesouro.glb')
