/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bauDoTesouro.glb 
*/

import { useRef, useState } from 'react'

import { useGLTF } from '@react-three/drei'

import { useSpring, animated } from '@react-spring/three'

export default function Bau({ set_interface , ativado , ...props }) {

  const { nodes, materials } = useGLTF('/models/bauDoTesouro.glb')

  const tampa = useRef(null)

  //animação da tampa do bau
  const { rotacaoTampa } = useSpring({

      rotacaoTampa: ativado ? [-1.3, 0, 0] : [1.6, 0, 0],
      
      config: { tension: 120, friction: 14 }
  
  })

  //animação do bau
  const { bauEscala , bauRotacao , bauPosicao } = useSpring({

    bauRotacao: ativado ? [0.9, 0, -.05] : [0, .1, 0],

    bauEscala : ativado ? [2, 2, 2] : [1, 1, 1],

    bauPosicao : ativado ? [.1, .35, .4] : [0, 0, 0],
      
    config: { tension: 200, friction: 20 },

    onStart: () => {
      if (!ativado) {
        set_interface(null)
      }
    },

    onRest: () => {
      if (ativado) {
        set_interface("bau")
      }
    }
  })

  return (

    <group {...props} >
      
      {/* bau */}
      <animated.group
        rotation={bauRotacao}
        position={bauPosicao} 
        scale={bauEscala}
        dispose={null}
      
        onPointerDown={ () => {

          if (!ativado) return       
        
        } }>

        <animated.group
        ref={tampa}
        rotation = { rotacaoTampa }
        position={[-0.172, 0.429, -0.285]} >

          <mesh 
            geometry={nodes.Lid.geometry} 
            material={materials.chests} 
          />

          <animated.group position={[ .17, .63 ,-.05 ]} rotation={[-Math.PI / 2, -Math.PI / 1 , 0]} >
            <mesh geometry={nodes.Object_4.geometry} material={materials['Material.010']} rotation={[0, -1.565, 0]} scale={[0.061, 0.064, 0.08]} />
            <mesh geometry={nodes.Object_10.geometry} material={materials['Material.012']} position={[-.0, .0, -.06]} rotation={[0, -1.565, 0.369]} scale={[0.006, 0.02, 0.018]} />
            <mesh geometry={nodes.Object_6.geometry} material={materials['Material.011']} rotation={[1.206, -1.535, 1.3]} scale={[0.104, 0.104, 0.085]} />
            <mesh geometry={nodes.Object_8.geometry} material={materials['Material.011']} scale={[0.104, 0.104, 0.085]} rotation={[-2.686, -1.524, 0.5]} />
          </animated.group>

        </animated.group>

        <mesh geometry={nodes.Box.geometry} material={materials.chests} />

        <mesh geometry={nodes.Gold.geometry}  material={materials.chests} position={[0, 0.379, 0]}  />       

      </animated.group>

      < pointLight position={[0,.5,0]} intensity={15} color={"#be9200"} />

    </group>

  )
  
}

useGLTF.preload('/models/bauDoTesouro.glb')
