/* eslint-disable react-hooks/purity */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 moeda_caveira.glb 
*/

import { useGLTF } from '@react-three/drei'
import { InstancedMesh, Object3D } from 'three'
import { useRef, useMemo, useLayoutEffect } from 'react'

export function Moedas_caveira({quantidade, espacamento}) {

  const { nodes, materials, scene } = useGLTF('modelos_cenas/bau/moeda_caveira.glb')

  const inclinacao = .15

    const geometria = useMemo(() => {
      // Tenta pegar diretamente pelo nome do mesh
      let geo = nodes.bitcoin_Material_0?.geometry
      if (geo) return geo

      // Se não, percorre a cena em busca do primeiro mesh com geometria
      let found = null
      scene.traverse((child) => {
        if (child.isMesh && child.geometry && !found) {
          found = child.geometry
        }
      })
      return found
    }, [nodes, scene ])

  const material = materials['Material.001']

  const moedas = useRef(null)

  {/* CRIA POSICAO< ROTACAO E ESCALA ALEATORIA PARA TODAS AS MOEDAS */}
    const { posicoes, rotacoes, escalas } = useMemo(() => {
      const posicoes = new Array(quantidade);
      const rotacoes = new Array(quantidade);
      const escalas = new Float32Array(quantidade);
  
      for (let i = 0; i < quantidade; i++) {
  
        const nova_posicao = {
          // eslint-disable-next-line react-hooks/purity
          x : (Math.random() - 0.5) * espacamento,
          y : (Math.random() - 0.5) * espacamento * 0.3,
          z : (Math.random() - 0.5) * espacamento,
        }
  
        const nova_rotacao = {
          x : Math.random() * Math.PI * 2,
          y : (Math.random() - .5) * inclinacao,
          z : (Math.random() - .5) * inclinacao,
        }
  
        posicoes[i] = nova_posicao
        rotacoes[i] = nova_rotacao      
        escalas[i] = 0.8 + Math.random() * 0.4; // variação de tamanho
      }
      return { posicoes, rotacoes, escalas };
    }, [quantidade, espacamento]);
  
  useLayoutEffect(() => {
  
      console.log("aass")
  
      if (!moedas.current) return
  
      console.log(posicoes)
  
      for (let i = 0; i < quantidade; i++) {
  
        const nova_moeda = new Object3D()
  
        nova_moeda.position.set(
          posicoes[i].x,
          posicoes[i].y,
          posicoes[i].z
        )
  
        nova_moeda.rotation.set(
          rotacoes[i].x,
          rotacoes[i].y,
          rotacoes[i].z,
        )
  
        nova_moeda.scale.setScalar(escalas[i])
  
        nova_moeda.updateMatrix()
        moedas.current.setMatrixAt(i, nova_moeda.matrix)
  
      }
  
      moedas.current.instanceMatrix.needsUpdate = true;
  
    }, [moedas])

  return (
    <instancedMesh
      ref={moedas}
      args={[geometria, material, quantidade]}
      castShadow={false}
      receiveShadow={false}
    />
  )
}

useGLTF.preload('modelos_cenas/bau/moeda_caveira.glb')
