/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gemas.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model({ ...props}) {
  const { nodes, materials } = useGLTF('/gemas.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Gemstone_01.geometry} material={materials['V_05.001']}  rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_01001.geometry} material={materials['V_04.001']} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_01002.geometry} material={materials['V_03.001']} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_01003.geometry} material={materials['V_02.001']} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_01004.geometry} material={materials['V_01.001']} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_02.geometry} material={materials['V_05.001']}  rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_02001.geometry} material={materials['V_04.001']} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_02002.geometry} material={materials['V_03.001']} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_02003.geometry} material={materials['V_02.001']} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_02004.geometry} material={materials['V_01.001']} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_03.geometry} material={materials['V_05.001']} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_03001.geometry} material={materials['V_04.001']} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_03002.geometry} material={materials['V_03.001']} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_03003.geometry} material={materials['V_02.001']} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_03004.geometry} material={materials['V_01.001']} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_04.geometry} material={materials['V_05.001']} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_04001.geometry} material={materials['V_04.001']} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_04002.geometry} material={materials['V_03.001']} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_04003.geometry} material={materials['V_02.001']} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_04004.geometry} material={materials['V_01.001']} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_05.geometry} material={materials['V_05.001']} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_05001.geometry} material={materials['V_04.001']} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_05002.geometry} material={materials['V_03.001']} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_05003.geometry} material={materials['V_02.001']} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_05004.geometry} material={materials['V_01.001']} rotation={[0.239, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/gemas.glb')
