/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gemas.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gemas.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Gemstone_01.geometry} material={materials['V_05.001']} position={[-2.835, 0.951, 0]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_01001.geometry} material={materials['V_04.001']} position={[-2.835, 1.953, -0.2]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_01002.geometry} material={materials['V_03.001']} position={[-2.835, 2.954, -0.4]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_01003.geometry} material={materials['V_02.001']} position={[-2.835, 3.956, -0.6]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_01004.geometry} material={materials['V_01.001']} position={[-2.835, 4.958, -0.8]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_02.geometry} material={materials['V_05.001']} position={[-1.418, 1, -0.006]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_02001.geometry} material={materials['V_04.001']} position={[-1.418, 1.998, -0.206]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_02002.geometry} material={materials['V_03.001']} position={[-1.418, 2.996, -0.406]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_02003.geometry} material={materials['V_02.001']} position={[-1.418, 3.994, -0.606]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_02004.geometry} material={materials['V_01.001']} position={[-1.418, 4.993, -0.806]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_03.geometry} material={materials['V_05.001']} position={[0, 1, 0]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_03001.geometry} material={materials['V_04.001']} position={[0, 2, -0.2]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_03002.geometry} material={materials['V_03.001']} position={[0, 3, -0.4]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_03003.geometry} material={materials['V_02.001']} position={[0, 4, -0.6]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_03004.geometry} material={materials['V_01.001']} position={[0, 5, -0.8]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_04.geometry} material={materials['V_05.001']} position={[1.418, 1, 0]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_04001.geometry} material={materials['V_04.001']} position={[1.418, 1.992, -0.2]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_04002.geometry} material={materials['V_03.001']} position={[1.418, 2.984, -0.4]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_04003.geometry} material={materials['V_02.001']} position={[1.418, 3.975, -0.6]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_04004.geometry} material={materials['V_01.001']} position={[1.418, 4.967, -0.8]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_05.geometry} material={materials['V_05.001']} position={[2.835, 1, 0]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_05001.geometry} material={materials['V_04.001']} position={[2.835, 1.997, -0.2]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_05002.geometry} material={materials['V_03.001']} position={[2.835, 2.993, -0.4]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_05003.geometry} material={materials['V_02.001']} position={[2.835, 3.99, -0.6]} rotation={[0.239, 0, 0]} />
      <mesh geometry={nodes.Gemstone_05004.geometry} material={materials['V_01.001']} position={[2.835, 4.987, -0.8]} rotation={[0.239, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/gemas.glb')
